table CreditRisk
	lineageTag: 2f96c1ca-8bdf-4716-ac5c-0ff41a20e623

	column client_ID
		dataType: string
		lineageTag: 657a9f41-53d5-4e17-bded-3d862e9f47d0
		summarizeBy: none
		sourceColumn: client_ID

		annotation SummarizationSetBy = Automatic

	column person_age
		dataType: int64
		formatString: 0
		lineageTag: db30cb5e-f8b0-42d5-ab93-dc0f37313b2b
		summarizeBy: sum
		sourceColumn: person_age

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"CreditRisk","TableItemName":"Age Group","ObjectType":4},"LinkType":"UsedInGroup"}]

	column person_income
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 101d3212-cff0-473c-80a9-5157785a2024
		summarizeBy: sum
		sourceColumn: person_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column person_home_ownership
		dataType: string
		lineageTag: 5bced078-4abc-4c07-ac44-d4859a59cba7
		summarizeBy: none
		sourceColumn: person_home_ownership

		annotation SummarizationSetBy = Automatic

	column person_emp_length
		dataType: double
		formatString: 0
		lineageTag: 4875cce1-9f8b-41e6-8307-007dc211870d
		summarizeBy: sum
		sourceColumn: person_emp_length

		annotation SummarizationSetBy = Automatic

	column loan_intent
		dataType: string
		lineageTag: 6618184c-6594-48f7-bcf6-de1bcbe87690
		summarizeBy: none
		sourceColumn: loan_intent

		annotation SummarizationSetBy = Automatic

	column loan_grade
		dataType: string
		lineageTag: 38cda90e-defe-4eae-bcca-08deebff9eb7
		summarizeBy: none
		sourceColumn: loan_grade

		annotation SummarizationSetBy = Automatic

	column loan_amnt
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ce2ac456-40c9-416b-b06f-a80fa958f9f9
		summarizeBy: sum
		sourceColumn: loan_amnt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column loan_int_rate
		dataType: double
		lineageTag: 42a17695-5804-4cf3-bee9-8b4d9ed99b69
		summarizeBy: sum
		sourceColumn: loan_int_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column loan_status
		dataType: int64
		formatString: 0
		lineageTag: 19c75bd6-8d53-4689-afa8-39f68b4942d8
		summarizeBy: sum
		sourceColumn: loan_status

		annotation SummarizationSetBy = Automatic

	column loan_percent_income
		dataType: double
		lineageTag: cd623cdb-42b8-43ed-993b-1928e8dc4331
		summarizeBy: sum
		sourceColumn: loan_percent_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cb_person_default_on_file
		dataType: string
		lineageTag: 2ff18ae0-8e94-4a09-95d9-0119fe2b0ff5
		summarizeBy: none
		sourceColumn: cb_person_default_on_file

		annotation SummarizationSetBy = Automatic

	column cb_person_cred_hist_length
		dataType: int64
		formatString: 0
		lineageTag: 98a7c957-feb0-4590-b37b-e89abfa5bb73
		summarizeBy: sum
		sourceColumn: cb_person_cred_hist_length

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 0a94f039-abf8-41c5-8c89-0ebdcee8a1dc
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		lineageTag: ca2d3714-f0f9-43af-a48f-9dd9b0776f69
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column education_level
		dataType: string
		lineageTag: 042b64e9-a193-4af3-a413-d9f5979bee10
		summarizeBy: none
		sourceColumn: education_level

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 32cd9802-50c1-4883-badd-1a7e424a99e6
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 5c588c60-08d7-4394-8fed-2bb273527c59
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: eb131e31-2b34-4341-babb-1c7c10a1459b
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column city_latitude
		dataType: double
		lineageTag: cbbc32eb-7f5e-4b0b-a5cd-ecf8b94e7f37
		summarizeBy: sum
		sourceColumn: city_latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column city_longitude
		dataType: double
		lineageTag: 4135a08c-6c01-4eb5-8544-7861ad78d2fa
		summarizeBy: sum
		sourceColumn: city_longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column employment_type
		dataType: string
		lineageTag: 72a24805-ed99-4002-a9ea-41476e57d4ef
		summarizeBy: none
		sourceColumn: employment_type

		annotation SummarizationSetBy = Automatic

	column loan_term_months
		dataType: int64
		formatString: 0
		lineageTag: 86181e99-2a3d-4b9a-9b0e-1f26c06ad148
		summarizeBy: sum
		sourceColumn: loan_term_months

		annotation SummarizationSetBy = Automatic

	column loan_to_income_ratio
		dataType: double
		lineageTag: 7ca43f13-a482-4e11-a288-877c83b6fa9e
		summarizeBy: sum
		sourceColumn: loan_to_income_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column other_debt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2739cc11-dafe-4d42-9c55-1f3228ecb06c
		summarizeBy: sum
		sourceColumn: other_debt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column debt_to_income_ratio
		dataType: double
		lineageTag: 34845afa-74bc-4fe3-9218-9cc1a41ed684
		summarizeBy: sum
		sourceColumn: debt_to_income_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column open_accounts
		dataType: int64
		formatString: 0
		lineageTag: ce15550b-3bf1-4a6f-a56b-ea042636fc94
		summarizeBy: sum
		sourceColumn: open_accounts

		annotation SummarizationSetBy = Automatic

	column credit_utilization_ratio
		dataType: double
		lineageTag: 9a3cb8c6-1dab-4e46-a056-5267eccb53cd
		summarizeBy: sum
		sourceColumn: credit_utilization_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column past_delinquencies
		dataType: int64
		formatString: 0
		lineageTag: 5be791ef-8386-4b53-b8fc-e6b2a0cc3aa9
		summarizeBy: sum
		sourceColumn: past_delinquencies

		annotation SummarizationSetBy = Automatic

	column 'Risk Flag'
		dataType: string
		lineageTag: 5571ef79-21c7-4bfe-a0b9-4b19c259d946
		summarizeBy: none
		sourceColumn: Risk Flag

		annotation SummarizationSetBy = Automatic

	column 'State City' = CreditRisk[state] & ", " & CreditRisk[city]
		lineageTag: fa153649-ace2-4099-aac4-39535ee720c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Age Group' =
			IF(
				ISBLANK('CreditRisk'[person_age]),
				BLANK(),
				INT('CreditRisk'[person_age] / 10) * 10
			)
		formatString: 0
		lineageTag: 7dcc863f-136c-4cd0-9e7d-afbc5389440c
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "CreditRisk"
				          }
				        },
				        "Property": "person_age"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 10.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"c","Entity":"CreditRisk"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"person_age"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"person_age"}},"Size":10.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'High Risk Borrower' =
			
			IF(
			    CreditRisk[debt_to_income_ratio] > 0.4 ||
			    CreditRisk[credit_utilization_ratio] > 0.7 ||
			    CreditRisk[past_delinquencies] > 0,
			    "High Risk",
			    "Low Risk"
			)
		lineageTag: 87f4c4cb-ebca-4fe8-8ded-4dba796f5a5c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Credit Risk' = ```
			
			IF(
			    CreditRisk[credit_utilization_ratio] > 0.7 ||
			    CreditRisk[past_delinquencies] > 0 ||
			    CreditRisk[cb_person_default_on_file] = "Y",
			    "High Risk",
			    "Low Risk"
			)
			
			```
		lineageTag: 6fa4b93e-09e8-44d5-ad20-e34f54c415fe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Loan Status' =
			
			IF(
			    CreditRisk[loan_status] = 1,
			    "Defualt",
			    "Non-Default"
			)
		lineageTag: 67d1ae78-d141-4fa3-9157-dc266d3eda93
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition CreditRisk = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://relianceinfo.sharepoint.com/sites/BusinessApplication", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Folder Path], "Data Analyst Squad")),
				    #"Credit_Risk_Dataset_Onyx_Data_September_25 xlsx_https://relianceinfo sharepoint com/sites/BusinessApplication/Shared Documents/_Training/_Internal/Data Analyst Squad/Credit Risk Assignment/" = #"Filtered Rows"{[Name="Credit_Risk_Dataset_Onyx_Data_September_25.xlsx",#"Folder Path"="https://relianceinfo.sharepoint.com/sites/BusinessApplication/Shared Documents/_Training/_Internal/Data Analyst Squad/Credit Risk Assignment/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Credit_Risk_Dataset_Onyx_Data_September_25 xlsx_https://relianceinfo sharepoint com/sites/BusinessApplication/Shared Documents/_Training/_Internal/Data Analyst Squad/Credit Risk Assignment/"),
				    #"Credit Risk Data_Sheet" = #"Imported Excel Workbook"{[Item="Credit Risk Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Credit Risk Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"client_ID", type text}, {"person_age", Int64.Type}, {"person_income", Currency.Type}, {"person_home_ownership", type text}, {"person_emp_length", Int64.Type}, {"loan_intent", type text}, {"loan_grade", type text}, {"loan_amnt", Currency.Type}, {"loan_int_rate", type number}, {"loan_status", Int64.Type}, {"loan_percent_income", type number}, {"cb_person_default_on_file", type text}, {"cb_person_cred_hist_length", Int64.Type}, {"gender", type text}, {"marital_status", type text}, {"education_level", type text}, {"country", type text}, {"state", type text}, {"city", type text}, {"city_latitude", type number}, {"city_longitude", type number}, {"employment_type", type text}, {"loan_term_months", Int64.Type}, {"loan_to_income_ratio", type number}, {"other_debt", Currency.Type}, {"debt_to_income_ratio", type number}, {"open_accounts", Int64.Type}, {"credit_utilization_ratio", type number}, {"past_delinquencies", Int64.Type}}),
				    #"Multiplied Column" = Table.TransformColumns(#"Changed Type", {{"loan_percent_income", each _ * 100, type number}}),
				    #"Added Custom" = Table.AddColumn(#"Multiplied Column", "Risk Flag", each if [loan_status] = 1 then "Default" else "Non Default"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Risk Flag", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1",null,0,Replacer.ReplaceValue,{"loan_int_rate"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,0,Replacer.ReplaceValue,{"person_emp_length"}),
				    #"Y to Yes person default" = Table.ReplaceValue(#"Replaced Value1","Y","Yes",Replacer.ReplaceText,{"cb_person_default_on_file"}),
				    #"N to No person default" = Table.ReplaceValue(#"Y to Yes person default","N","Yes",Replacer.ReplaceText,{"cb_person_default_on_file"})
				in
				    #"N to No person default"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

